- name: giving varible values in inventory files
  hosts: local
  connection: local
  tasks:
  - name: print course details
    ansible.builtin.debug:
      msg: "print the course name is {{ course }} and its long is {{ duration }}"

  # ansible-playbook -i inventory.ini 11-vars-argumentthrhcmd.yaml -e "course=dev duration=10hrs" this need torun in cmd
    