- name: checks whether loops are working fine or not
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "hello {{ items }}"
    loop:
    - jay
    - ajay
    - arjun 