- name: functions
  hosts: local
  connection: local
  vars:
    Person: Jayapal Reddy
  tasks:
  - name: checking person
    ansible.builtin.debug:
      msg: "Hello {{ Person | default ('Ramesh') }}"

  - name: checking person
    ansible.builtin.debug:
      msg: "Hello {{ Person | upper }}"

  - name: checking person
    ansible.builtin.debug:
      msg: "Hello {{ Person | lower }}"