- name: install nginx
  hosts: local
  become: yes
  connection: local
  tags:
  - check
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
   

  - name: start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes