- name: install nginx
  hosts: local
  become: yes
  connection: local
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
      tags:
      - check

  - name: start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes