- name: play2
  hosts: local
  connection: local
  vars_files:
  - secret.yaml
  tasks:
  - name: hello from play2 and task 1
    ansible.builtin.debug:
      msg: "hello from {{ db_user }}"

  - name: hello from play2 and task 2
    ansible.builtin.debug:
      msg: "hello from {{ db_password }}"